### ISSUE TITLE
NPE in PatchDiffViewer when comparing jsons containing empty json objects

### ISSUE THREAD

**Issue by aymar99** [deblockt/json-diff#14]
Steps to reproduce

Run the [Sample.java](https://github.com/deblockt/json-diff/blob/1383772beb69d9e2e169ea79b258a9f8b47a57fd/src/test/java/com/deblock/jsondiff/Sample.java) with

Test case 1
expected - `{}`
actual - `{}`

Test case 2
expected - `{
	"a": {}
}`
actual - `{
	"a": {}
}`

NPE will be thrown as below
`Exception in thread "main" java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "diff" is null
	at com.deblock.jsondiff.viewer.PatchDiffViewer.toDiff(PatchDiffViewer.java:153)
	at com.deblock.jsondiff.viewer.PatchDiffViewer.toString(PatchDiffViewer.java:98)
	at java.base/java.lang.String.valueOf(String.java:4215)
	at java.base/java.io.PrintStream.println(PrintStream.java:1047)
	at com.deblock.jsondiff.Sample.main(Sample.java:34)`

**Comment by deblockt** [comment]
fixed on `1.0.1` version
